function EEGdata = ProcessStatus(EEGdata, processName, processValue)
%PROCESSSTATUS 初始化或更新EEGdata.Process处理状态表。
%   EEGdata = ProcessStatus(EEGdata)补齐全部已知步骤，默认值为0。
%   EEGdata = ProcessStatus(EEGdata,name,value)将指定步骤设置为0或1。
%   只有步骤真正成功完成后才应设置为1；跳过、取消和异常保持0。

    defaults = struct( ...
        'bdf_import', 0, ...
        'marker_extract', 0, ...
        'marker_auto', 0, ...
        'marker_manual', 0, ...
        'segment', 0, ...
        'artifact_auto', 0, ...
        'artifact_manual', 0, ...
        'artifact_segment', 0, ...
        'artifact_complete', 0, ...
        'resample', 0, ...
        'detrend', 0, ...
        'bandpass', 0, ...
        'notch', 0, ...
        'reference', 0, ...
        'preprocess_auto', 0, ...
        'robust', 0, ...
        'asr', 0, ...
        'ica', 0, ...
        'ica_auto', 0, ...
        'ica_manual', 0, ...
        'preprocess_manual', 0, ...
        'preprocess_complete', 0);

    if ~isstruct(EEGdata) || ~isscalar(EEGdata)
        error("EEGdata必须为标量结构体。");
    end

    if ~isfield(EEGdata, 'Process') || ...
            ~isstruct(EEGdata.Process) || ...
            ~isscalar(EEGdata.Process)
        EEGdata.Process = struct();
    end

    processFields = fieldnames(defaults);

    for ifield = 1:numel(processFields)
        currentField = processFields{ifield};

        if ~isfield(EEGdata.Process, currentField)
            EEGdata.Process.(currentField) = defaults.(currentField);
        end
    end

    if nargin < 2 || isempty(processName)
        return;
    end

    if nargin < 3
        processValue = 1;
    end

    validateattributes(processValue, {'numeric', 'logical'}, ...
        {'scalar'});

    if ~ismember(double(processValue), [0, 1])
        error("Process状态值只能为0或1。");
    end

    processName = string(processName(:)');

    for iprocess = 1:numel(processName)
        currentName = char(processName(iprocess));

        if ~isfield(defaults, currentName)
            error("未知Process步骤：%s", currentName);
        end

        EEGdata.Process.(currentName) = double(processValue);
    end

end
